"""add_version_column_to_farm_plots

Revision ID: 5c9795318a6d
Revises: b5dad37c3777
Create Date: 2026-08-16 20:40:13.582076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9795318a6d'
down_revision: Union[str, Sequence[str], None] = 'b5dad37c3777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_plots', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm_plots', 'version')
    # ### end Alembic commands ###
