"""initial_schema_and_date_conversion

Revision ID: 782bf1469fc1
Revises: 
Create Date: 2026-08-16 20:02:20.924495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782bf1469fc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farm_plots', 'sowing_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               postgresql_using='sowing_date::date',
               existing_nullable=False)
    op.create_index(op.f('ix_farm_plots_user_id'), 'farm_plots', ['user_id'], unique=False)
    op.alter_column('irrigation_logs', 'applied_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               postgresql_using='applied_date::date',
               existing_nullable=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('irrigation_logs', 'applied_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_farm_plots_user_id'), table_name='farm_plots')
    op.alter_column('farm_plots', 'sowing_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
